version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: jogo-do-bicho-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jogo-do-bicho
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/var/lib/postgres
    networks:
      - main

  api:
    build: ./
    container_name: jogo-do-bicho
    restart: always
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main

networks:
  main:
