services:
  db:
    image: mysql
    container_name: jogo-do-bicho-db
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jogo-do-bicho
    ports:
      - 3306:3306
    volumes:
      - ./sql/init/:/docker-entrypoint-initdb.d
      - ./sql/tmp/mysql:/var/lib/mysql
    networks:
      - main

  api:
    build: ./
    container_name: jogo-do-bicho
    restart: always
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main

networks:
  main:
