FROM golang:1.21 AS build-stage

WORKDIR /app 

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLE=1 GOOS=linux go build -o /jogo-do-bicho ./cmd/api/main.go


FROM build-stage AS run-test-stage
RUN go test -v ./...


FROM gcr.io/distroless/base-debian12 AS build-release-stage

WORKDIR /

COPY --from=build-stage /jogo-do-bicho /jogo-do-bicho

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/jogo-do-bicho"]