services:
  db:
    image: mysql
    container_name: jogo-do-bicho-db
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jogo-do-bicho
    ports:
      - 3306:3306
    volumes:
      - ./sql/init/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/schemas/gambler.sql:/docker-entrypoint-initdb.d/2.sql
      - ./sql/schemas/bet_group.sql:/docker-entrypoint-initdb.d/3.sql
      - ./sql/schemas/raffle.sql:/docker-entrypoint-initdb.d/4.sql
      - ./sql/schemas/bet.sql:/docker-entrypoint-initdb.d/5.sql
      - ./sql/tmp/mysql:/var/lib/mysql
    networks:
      - main

  api:
    build: ./
    container_name: jogo-do-bicho
    restart: always
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main

networks:
  main:
