GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';

USE `jogo-do-bicho`;

CREATE TABLE IF NOT EXISTS gamblers (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  gambler_name VARCHAR(50) NOT NULL,
  document VARCHAR(20) NOT NULL,
  document_type ENUM('CPF', 'RG') NOT NULL,
  birth_date VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raffles (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    raffle_edition INT NOT NULL,
    animal VARCHAR(255) NOT NULL,
    raffle_number VARCHAR(20) NOT NULL,
    raffle_order INT NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bets (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gambler_id BIGINT NOT NULL,
    bet_type VARCHAR(30) NOT NULL,
    bet_price FLOAT NOT NULL,
    bet_choice VARCHAR(50) NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_gambler FOREIGN KEY (gambler_id) REFERENCES gamblers(id)
);

CREATE TABLE IF NOT EXISTS bet_groups (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(30) NOT NULL,
    group_number VARCHAR(2) NOT NULL
);

INSERT INTO bet_groups (group_name, group_number) VALUES 
('AVESTRUZ', "01"),
('AVESTRUZ', "02"),
('AVESTRUZ', "03"),
('AVESTRUZ', "04"),
('ÁGUIA', "05"),
('ÁGUIA', "06"),
('ÁGUIA', "07"),
('ÁGUIA', "08"),
('BURRO', "09"),
('BURRO', "10"),
('BURRO', "11"),
('BURRO', "12"),
('BORBOLETA', "13"),
('BORBOLETA', "14"),
('BORBOLETA', "15"),
('BORBOLETA', "16"),
('CACHORRO', "17"),
('CACHORRO', "18"),
('CACHORRO', "19"),
('CACHORRO', "20"),
('CABRA', "21"),
('CABRA', "22"),
('CABRA', "23"),
('CABRA', "24"),
('CARNEIRO', "25"),
('CARNEIRO', "26"),
('CARNEIRO', "27"),
('CARNEIRO', "28"),
('CAMELO', "29"),
('CAMELO', "30"),
('CAMELO', "31"),
('CAMELO', "32"),
('COBRA', "33"),
('COBRA', "34"),
('COBRA', "35"),
('COBRA', "36"),
('COELHO', "37"),
('COELHO', "38"),
('COELHO', "39"),
('COELHO', "40"),
('CAVALO', "41"),
('CAVALO', "42"),
('CAVALO', "43"),
('CAVALO', "44"),
('ELEFANTE', "45"),
('ELEFANTE', "46"),
('ELEFANTE', "47"),
('ELEFANTE', "48"),
('GALO', "49"),
('GALO', "50"),
('GALO', "51"),
('GALO', "52"),
('GATO', "53"),
('GATO', "54"),
('GATO', "55"),
('GATO', "56"),
('JACARÉ', "57"),
('JACARÉ', "58"),
('JACARÉ', "59"),
('JACARÉ', "60"),
('LEÃO', "61"),
('LEÃO', "62"),
('LEÃO', "63"),
('LEÃO', "64"),
('MACACO', "65"),
('MACACO', "66"),
('MACACO', "67"),
('MACACO', "68"),
('PORCO', "69"),
('PORCO', "70"),
('PORCO', "71"),
('PORCO', "72"),
('PAVÃO', "73"),
('PAVÃO', "74"),
('PAVÃO', "75"),
('PAVÃO', "76"),
('PERU', "77"),
('PERU', "78"),
('PERU', "79"),
('PERU', "80"),
('TOURO', "81"),
('TOURO', "82"),
('TOURO', "83"),
('TOURO', "84"),
('TIGRE', "85"),
('TIGRE', "86"),
('TIGRE', "87"),
('TIGRE', "88"),
('URSO', "89"),
('URSO', "90"),
('URSO', "91"),
('URSO', "92"),
('VEADO', "93"),
('VEADO', "94"),
('VEADO', "95"),
('VEADO', "96"),
('VACA', "97"),
('VACA', "98"),
('VACA', "99"),
('VACA', "00");