// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: bet.sql

package db

import (
	"context"
)

const createBet = `-- name: CreateBet :one
INSERT INTO
    bets (gambler_id, bet_type, bet_price, bet_choice)
VALUES
    ($1, $2, $3, $4) RETURNING id, gambler_id, bet_type, bet_price, bet_choice
`

type CreateBetParams struct {
	GamblerID int32   `db:"gambler_id" json:"gambler_id"`
	BetType   string  `db:"bet_type" json:"bet_type"`
	BetPrice  float64 `db:"bet_price" json:"bet_price"`
	BetChoice string  `db:"bet_choice" json:"bet_choice"`
}

func (q *Queries) CreateBet(ctx context.Context, arg CreateBetParams) (Bet, error) {
	row := q.db.QueryRow(ctx, createBet,
		arg.GamblerID,
		arg.BetType,
		arg.BetPrice,
		arg.BetChoice,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.GamblerID,
		&i.BetType,
		&i.BetPrice,
		&i.BetChoice,
	)
	return i, err
}

const getBet = `-- name: GetBet :one
SELECT
    bets.id, bets.gambler_id, bets.bet_type, bets.bet_price, bets.bet_choice,
    gamblers.id, gamblers.gambler_name, gamblers.document, gamblers.document_type, gamblers.birth_date
FROM
    bets
    JOIN gamblers ON bets.gambler_id = gamblers.id
WHERE
    bets.id = $1
`

type GetBetRow struct {
	Bet     Bet     `db:"bet" json:"bet"`
	Gambler Gambler `db:"gambler" json:"gambler"`
}

func (q *Queries) GetBet(ctx context.Context, id int32) (GetBetRow, error) {
	row := q.db.QueryRow(ctx, getBet, id)
	var i GetBetRow
	err := row.Scan(
		&i.Bet.ID,
		&i.Bet.GamblerID,
		&i.Bet.BetType,
		&i.Bet.BetPrice,
		&i.Bet.BetChoice,
		&i.Gambler.ID,
		&i.Gambler.GamblerName,
		&i.Gambler.Document,
		&i.Gambler.DocumentType,
		&i.Gambler.BirthDate,
	)
	return i, err
}

const getBets = `-- name: GetBets :many
SELECT
    bets.id, bets.gambler_id, bets.bet_type, bets.bet_price, bets.bet_choice,
    gamblers.id, gamblers.gambler_name, gamblers.document, gamblers.document_type, gamblers.birth_date
FROM
    bets
    JOIN gamblers ON bets.gambler_id = gamblers.id
`

type GetBetsRow struct {
	Bet     Bet     `db:"bet" json:"bet"`
	Gambler Gambler `db:"gambler" json:"gambler"`
}

func (q *Queries) GetBets(ctx context.Context) ([]GetBetsRow, error) {
	rows, err := q.db.Query(ctx, getBets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBetsRow
	for rows.Next() {
		var i GetBetsRow
		if err := rows.Scan(
			&i.Bet.ID,
			&i.Bet.GamblerID,
			&i.Bet.BetType,
			&i.Bet.BetPrice,
			&i.Bet.BetChoice,
			&i.Gambler.ID,
			&i.Gambler.GamblerName,
			&i.Gambler.Document,
			&i.Gambler.DocumentType,
			&i.Gambler.BirthDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
