// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Bet struct {
	ID        sql.NullInt32
	Animal    string
	BetNumber int32
	BetPrice  string
}
